import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../Components/Navbar'
 

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <main className="bg-white my-3 text-gray-800 opacity-60 rounded-xl mx-auto z-0 w-9/12 px-9 pb-7 " >
    <div className="1st">
      <h1 className='font-bold text-3xl text-center py-8 '>Covid-19 Stay Home Stay Safe</h1>
      <h2 className='font-bold text-2xl py-3 '>#IndiaFightsCorona COVID-19</h2>
      <p className=''>Government of India is taking all necessary steps to ensure that we are prepared well to face the challenge and threat posed by the growing pandemic of COVID-19 the Corona Virus. The most important factor in preventing the spread of the Virus locally is to empower the citizens with the right information and taking precautions as per the advisories being issued by Ministry of Health & Family Welfare Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus, natus expedita? Molestias ipsa laudantium consectetur necessitatibus nam quasi ratione veritatis non magni magnam?</p>
    </div>
    <div className="2nd">
      <h2 className='font-bold text-2xl py-3 '>#StayHome - How to protect yourself</h2>
      <h3 className='font-bold text-lg'>Do</h3>
      <ul className='' >
          <li className='list-disc text-base ml-10'>Wash your hands regularly for 20 seconds, with soap and water or alcohol-based hand rub</li>
          <li className='list-disc text-base ml-10'>Cover your nose and mouth with a disposable tissue or flexed elbow when you cough or sneeze</li>
          <li className='list-disc text-base ml-10'>Cover your nose and mouth with a disposable tissue or flexed elbow when you cough or sneeze</li>
          <li className='list-disc text-base ml-10'>Cover your nose and mouth with a disposable tissue or flexed elbow when you cough or sneeze</li>
      </ul>
      <h3 className='font-bold text-lg'>Don'ts</h3>
      <ul className='' >
        <li className='list-disc text-base ml-10'>Touch your eyes, nose, or mouth if your hands are not clean</li>
      </ul>
    </div>
    <div className="3rd">
      <h2 className='font-bold text-2xl py-3 '>#FAQs - Frequently asked questions</h2>
      <h4 className=''>Q: What are the symptoms of the coronavirus disease?</h4>
      <p className=''>A: The most common symptoms are fever, cough, shortness of breath, and breathing difficulties. In more severe cases infection can cause pneumonia, severe acute respiratory syndrome, and even death. The period within which the symptoms would appear is 2-14 days.</p>

      <h4 className=''>Q: What is the recovery time for the coronavirus disease?</h4>
      <p className=''>A: Using available preliminary data, the median time from onset to clinical recovery for mild cases is approximately 2 weeks and is 3-6 weeks for patients with severe or critical disease.</p>

      <h4 className=''>Q: How long does the coronavirus last on surfaces?</h4>
      <p className=''>A: It is not certain how long the virus that causes COVID-19 survives on surfaces, but it seems to behave like other coronaviruses. Studies suggest that coronaviruses (including preliminary information on the COVID-19 virus) may persist on surfaces for a few hours or up to several days.</p>
    </div>
      </main>
 
    </div>
  )
}
